### ISSUE TITLE
私聊搜图后台显示发送了合并消息，但实际上没有消息并没有发出去。

### ISSUE THREAD

**Issue by Lynn-zy** [NekoAria/YetAnotherPicSearch#70]
### YetAnotherPicSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

> - YetAnotherPicSearch：1.7.8
> - go-cqhttp：nonebot中插件nonebot_plugin_gocqhttp自带的go-cq
> - nonebot：[v2.0.0rc3]
> - python：3.10.6
> - 操作系统：Windows

### 如何复现

私聊搜图没有结果，后台显示消息已发送。

### 实际行为

![123](https://user-images.githubusercontent.com/75057634/216353539-43652223-81b0-4417-8695-cc65988c61e4.png)

**Comment by Lynn-zy** [comment]
> 同一张图，你发到群里，然后让机器人搜图试试。
> 
> 我印象中，有时候会遇到这种情况—私聊收不到搜图结果合并转发消息，群聊又是正常的。不知道为什么。

- 如果先私聊bot，让bot搜图，后台会显示bot会直接回复或者用转发合并消息的方式回复，但是实际上bot并没有发送消息，我没收到。此时把同一张图发到群里让bot搜图，bot会在群里直接给出结果，然后会有[缓存]的提示。
- 如果先发到群里让bot搜图，bot可以成功搜图并给出结果，此时把同一张图私聊发给bot进行搜图，后台会显示bot已经发送了消息，然后Mater running complete，但实际上我还是没收到bot发送的消息。

会不会是好友私聊的接口出了问题（

**Comment by NekoAria** [comment]
应该是 gocq 那边的问题，你可以试试修改配置再看看。
例如 device.json 里的协议，还有 config.yml 里的一些配置项，具体看 [配置 | go-cqhttp 帮助中心](https://docs.go-cqhttp.org/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF) 。

**Comment by Lynn-zy** [comment]
> 应该是 gocq 那边的问题，你可以试试修改配置再看看。 例如 device.json 里的协议，还有 config.yml 里的一些配置项，具体看 [配置 | go-cqhttp 帮助中心](https://docs.go-cqhttp.org/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF) 。

config.yml已经是默认配置了，也尝试过把allow-temp-session（允许临时会话）改为true，即使我和bot已经是好友，但是也没有用，私聊还是收不到搜图的结果。虚拟设备使用的登录协议是MacOS，按照gocq的说明文档来看是没有问题和缺点的。

**Comment by NekoAria** [comment]
> config.yml已经是默认配置了，也尝试过把allow-temp-session（允许临时会话）改为true，即使我和bot已经是好友，但是也没有用，私聊还是收不到搜图的结果。虚拟设备使用的登录协议是MacOS，按照gocq的说明文档来看是没有问题和缺点的。

协议这点并不好说。
另外，是所有的图片都会遇到这个问题吗？
不是的话，我倒是可以也测试一下。

**Comment by Lynn-zy** [comment]
> > config.yml已经是默认配置了，也尝试过把allow-temp-session（允许临时会话）改为true，即使我和bot已经是好友，但是也没有用，私聊还是收不到搜图的结果。虚拟设备使用的登录协议是MacOS，按照gocq的说明文档来看是没有问题和缺点的。
> 
> 协议这点并不好说。 另外，是所有的图片都会遇到这个问题吗？ 不是的话，我倒是可以也测试一下。

所有的图片都是这样，群聊可以，私聊收不到结果

**Comment by NekoAria** [comment]
我很久没遇到过这个问题了。
贴一下我的 config.yml 的其中一部分吧：

```yml
message:
  # 上报数据类型
  # 可选: string,array
  post-format: string
  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false
  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: false
  # 是否将url分片发送
  fix-url: false
  # 下载图片等请求网络代理
  proxy-rewrite: ''
  # 是否上报自身消息
  report-self-message: false
  # 移除服务端的Reply附带的At
  remove-reply-at: false
  # 为Reply附加更多信息
  extra-reply-data: false
  # 跳过 Mime 扫描, 忽略错误数据
  skip-mime-scan: false
```

此外，我用的协议是 1 (Android Phone) 。
